#include "Cat.h"

void paintCat()
{
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                      " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                      " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                    " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "        " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "                                                        " << endl;
}

void paintListCat() {
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                                                    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                                    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    cout << "                    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    cout << "                      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                                " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                  " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                              " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                              " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                            " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                            " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                            " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                " << endl;
    cout << "                                                                " << endl;
}