#include "Menu.h"

void choiceSelector(int& value) {
    ConsoleClear();
    ConsoleXY(0, 0);
    paintCat();
    ConsoleXY(20, 12);
    ConsoleSetColor(DARKMAGENTA, LIGHTGREY);
    cout << "1. Play\n";
    ConsoleXY(19, 13);
    cout << "2. TOP 10\n";
    ConsoleXY(20, 14);
    cout << "0. Exit\n";
    ConsoleXY(23, 15);
    value = 0;
    while (value == 0) value = ConsoleInKey();
    ConsoleClear();
}

void playerName(Player* pointer)
{
    paintCat();
    ConsoleXY(15, 12);
    ConsoleSetColor(DARKMAGENTA, LIGHTGREY);
    cout << "What's your name?\n";
    ConsoleXY(19, 13);
    {
        string _auxiliaryName;
        cin >> _auxiliaryName;
        pointer->setName(_auxiliaryName);
    }
    ConsoleClear();
}

void writePointsFile(Player* pointer)
{
    fstream _handler;

    // Adding the points to the points list file of the top 10 best punctuations.
    _handler.open("PointsList.txt", ios::app); // Opening the file in the reading mode.

    //string intToString = to_string(_pCharacter->getPoints());
    _handler << pointer->getName() << "|" << pointer->getPoints() << ",";

    _handler.close(); // Closing the file. 
}

void readPointsFile()
{
    fstream _handler;
    string _pointsTexts, _pointText, _name, _points;
    vector<string> _listNames;
    vector<int> _listPoints;

    paintListCat();

    // Reading the points of the points list file and giving the top 10 best punctuations in screen.
    _handler.open("PointsList.txt", ios::in); // Opening the file in the reading mode.

    if (_handler.is_open()) {
        while (!_handler.eof()) { // Until is the end of the file we read.
            getline(_handler, _pointsTexts);
        }

        _handler.close(); // Closing the file

        while (_pointsTexts.find(44) != string::npos) { // Until it doesn't find a , will cut the names and the points and will save them.
            _pointText = _pointsTexts.substr(0, _pointsTexts.find(44)); // Cutting the name and the points.
            _name = _pointText.substr(0, _pointText.find(124)); // Separating the name.
            _points = _pointText.substr(_pointText.find(124) + 1); // Separating the points.

            _listPoints.push_back(stoi(_points)); // List of all the points to check the order later.
            _listNames.push_back(_points + " - " + _name); // List of the visual display to the user. List of name and points.

            _pointsTexts.erase(0, _pointsTexts.find(44) + 1); // Erase of the , to get another names.
        }

        for (size_t i = 0; i < _listPoints.size() - 1; i++) {
            for (size_t j = i + 1; j < _listPoints.size(); j++) {
                if (_listPoints[i] < _listPoints[j]) { // Ordering the points with the sawp function.
                    swap(_listPoints[i], _listPoints[j]);
                    swap(_listNames[i], _listNames[j]);
                }
            }
        }

        for (size_t i = 0; i < _listPoints.size() && i < 10; i++) {
            ConsoleXY(25, 3 + (short)i);
            ConsoleSetColor(DARKMAGENTA, WHITE);
            cout << _listNames[i] << endl; // Cout in the Paint Cat List.
        }

        _listNames.clear();
        _listPoints.clear();
    }
}

void paintCat()
{
    ConsoleClear();
    ConsoleXY(0, 0);
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                      " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                      " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                    " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "        " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "                                                        " << endl;
}

void paintListCat() {
    ConsoleClear();
    ConsoleXY(0, 0);
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                                                    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  " << endl;
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                                    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    cout << "                    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    cout << "                      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                        " << endl;
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                                                " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                  " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                              " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                              " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                            " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                            " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(MAGENTA, MAGENTA);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                            " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                          " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "              " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                  " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(WHITE, WHITE);
    cout << "                                " << endl;
    cout << "                                                                " << endl;
}

void paintWinnerCat()
{
    ConsoleClear();
    ConsoleXY(0, 0);
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                                                        " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                        " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                        " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                      " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                      " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                    " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                  " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
        ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(YELLOW, YELLOW);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "      " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "        " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKYELLOW, DARKYELLOW);
    cout << "                        " << endl;
    cout << "                                                        " << endl;
}

void paintLoserCat()
{
    ConsoleClear();
    ConsoleXY(0, 0);
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                                                        " << endl;
    cout << "                ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                        " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                        " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                      " << endl;
    cout << "            ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                      " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                    " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                    " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                      ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                  " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(RED, RED);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                  " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "    ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "        " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "    ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(RED, RED);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "                          ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "      " << endl;
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "      " << endl;
    cout << "        ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "    ";
    ConsoleSetColor(DARKGREY, DARKGREY);
    cout << "  ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "  ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "        " << endl;
    cout << "          ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "          ";
    ConsoleSetColor(LIGHTGREY, LIGHTGREY);
    cout << "  ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "                ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "          " << endl;
    cout << "              ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "      ";
    ConsoleSetColor(BLACK, BLACK);
    cout << "      ";
    ConsoleSetColor(DARKRED, DARKRED);
    cout << "                        " << endl;
    cout << "                                                        " << endl;
}